### ISSUE TITLE
[Bug]: i honestly have no idea whats happening here, but blocks are really broken on servers

### ISSUE THREAD

**Issue by slushieuwu** [Fuzss/diagonal-blocks#32]
### Mod Loader (Required)

Quilt

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.2.3

### Notes (Required)

when on a server, certain blocks change into other random blocks. doesnt happen in singleplayer

with the mod:
![image](https://user-images.githubusercontent.com/86991346/204162579-0d257b4a-5ce3-48c2-a22b-53abd6e8fffc.png)

without the mod:
![image](https://user-images.githubusercontent.com/86991346/204162612-a705c05d-23c6-4700-9b02-0d1928e298d7.png)

### latest.log (Optional)

https://mclo.gs/LEpKnsL

**Comment by slushieuwu** [comment]
im just lost for words on how this even happens

**Comment by Fuzss** [comment]
The server needs Diagonal Fences too, this not a client-only mod. This is only visual, no data is corrupted server-side. 

This happens as block states are synced via an index (I think?), and since there are more block states now with the diagonal fence states there is a mismatch between the block state maps on server and client.

**Comment by Fuzss** [comment]
The real bummer here is that Fabric even let’s you join a server when there is such a mismatch with client data, hopefully this will at some point be resolved on the mod loaders end. After all Forge properly prevents you from joining in such a scenario.

**Comment by slushieuwu** [comment]
wait i just realized, the diagonal glass panes mod works just fine on client only, couldnt you do what that mod does to make it functional on clientside?
