### ISSUE TITLE
[Suggestion]: diagonal elevation support

### ISSUE THREAD

**Issue by AlienXtream** [Fuzss/diagonal-blocks#35]
### Suggestion (Required)

due to the nature of the modifications i would assume that any mod that allows similar mechanics for elevation connections would cause issues. not that im aware of any mods that have anything like that. as such im making the suggestion for not just vertically diagonal fences but all the missing connection types. i do understand its a tedious undertaking to define the elements for, what is it? 24 directions? would make building sailing ships and banisters easier for sure :D

![image](https://user-images.githubusercontent.com/12606809/219548675-1a44f68f-35af-45fa-9722-bb62bbf811c0.png)

**Comment by SammyForReal** [comment]
I would love to see this feature too! If this addition also supports them being built freely in air, I could build supports for elevator shafts, leading to mines, much more beautifully too!

**Comment by Fuzss** [comment]
The technical implementation of a feature like this is.. challenging to say the least. The problem is Minecraft's block state system where all possible states of a block are evaluated during the game's launch (basically pre-built). Vanilla fences have $2^4\cdot2=32$ [total states](https://minecraft.fandom.com/wiki/Fence#Block_states), with the diagonal connections from Diagonal Fences this is already increased to $2^8\cdot2=512$. With your suggestions the total would be at $4^8\cdot2=131.072$ which is way too much as you can probably already tell.

A solution for this would be to use block entities which are able to store block data more freely and generate everything at runtime, but are very taxing on the game in a different way which makes them not feasible for blocks that are used in large quantities in builds (block entities are designed for functional blocks such as furnaces which there generally aren't a lot of).

So no, I won't be adding your suggestion unfortunately, although I enjoy the idea quite a lot actually.

**Comment by AlienXtream** [comment]
completely understandable. perhaps (maybe as a separate "sister" mod) you could have some sort of "banister" mod that does it as a normal block model with cardinal rotations. no diagonal, just the vanilla fence shape offset down one. 'tis a topic for later brainstorming though.
