### ISSUE TITLE
[Suggestion]: Diagonal Glass Panes

### ISSUE THREAD

**Issue by CyanideX** [Fuzss/diagonal-blocks#42]
### Suggestion

I realize this is not a fence (unless you wanted to add glass fences) but I would love to see a diagonal glass panes mod. 🙂

**Comment by Fuzss** [comment]
Well actually glass panes are the same as fences in code lol.
This is already implemented in the mod, just deactivated internally, since I want to release it as a separate project since well after all the mod is called diagonal fences haha.
If you tell me the mc version you are playing I can already send you a preview.
![](https://cdn.discordapp.com/attachments/917550806922846299/1107012638791188620/2023-05-13_20.32.16.png)

**Comment by CyanideX** [comment]
Looks beautiful! 😍 You've been holding out.

I am currently playing 1.19.2 and would love a preview. I really appreciate all the work you've done; your mods are a staple in my instance.

**Comment by HanatakeYurii** [comment]
Oh that would be awesome! Currently also on Forge 1.19.2 and I'll be waiting for this too.

**Comment by Fuzss** [comment]
Welp, that took longer than expected. Turns out I had diagonal panes working on every version but 1.19.2. 🙈
Just released a Diagonal Fences preview with diagonal panes enabled for 1.18.2, 1.19.2 and 1.20.1 on the Discord, you can download them over there in my channel: https://lunapixel.studio/discord

@CyanideX And thank you so much for the kind words! Big fan of your textures, was using Unity all the time back in the 1.7.10 era when I was still playing mods instead of making them. 😝

Leaving this open until diagonal panes are publicly released.

**Comment by Fuzss** [comment]
Here you go, diagonal windows are finally publicly released: https://legacy.curseforge.com/minecraft/mc-mods/diagonal-windows

**Comment by HanatakeYurii** [comment]
Thank you very much
