### ISSUE TITLE
Quark Gold Bars Illegal Argument Exception

### ISSUE THREAD

**Issue by AllieSniperian** [Fuzss/diagonal-blocks#8]
In testing, it'd appear that my game crashes when a structure is generating in the nether that uses Quark's Gold Bars crashes when the following exception occurs

java.lang.IllegalArgumentException: Cannot set property BooleanProperty{name=north_east, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{quark:gold_bars}
	at net.minecraft.state.StateHolder.func_206870_a(SourceFile:114) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:babel.mixins.json:StateHolderMixin,pl:mixin:APP:META-INF/diagonalfences.mixins.json:accessor.IStateHolderAccessor,pl:mixin:A}...

[crash-2021-10-19_13.15.53-server.txt](https://github.com/Fuzss/diagonalfences/files/7377229/crash-2021-10-19_13.15.53-server.txt)

This crash can be replicated by trying to enter the nether on v1.11.4 of Nutmeg that uses version v1.1.1 of Diagonal Fences, and version r2.4-319 of Quark, it is unknown if other mods are needed to recreate this issue, so the mod pack has been provided if that helps where the crash can be replicated.
https://www.curseforge.com/minecraft/modpacks/nutmeg-casual-pack

**Comment by Fuzss** [comment]
That's due to Quark generating gold bars in nether fortresses instead of the vanilla nether brick fences. 

Quark just copies all block states over from the original fence, without checking if the block state actually exists for gold bars. That's fine for vanilla, as both blocks have the same states, but with Diagonal Fences, fences have four more block states which gold bars do not have.

I'll see that I submit a PR to Quark for fixing this on their end asap.

**Comment by Fuzss** [comment]
Should be fixed as of Quark r2.4-320. If you cannot confirm that please reopen this issue.
